AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Stack - Step 4: VPC + Subnets + Security Groups + EC2'

Parameters:
  ProjectName:
    Type: String
    Default: aws-practice
    Description: Name of the project
  
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
    Default: aws-practice-keypair

Resources:
  # VPC Stack (from Step 1)
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../templates/vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-vpc-stack

  # Subnet Stack (from Step 2)
  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../templates/subnet.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-subnet-stack

  # Security Groups Stack (from Step 3)
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../templates/security-groups.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-sg-stack

  # EC2 Stack (New in Step 4)
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../templates/ec2.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnetId: !GetAtt SubnetStack.Outputs.PrivateSubnetId
        WebServerSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
        KeyPairName: !Ref KeyPairName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-ec2-stack

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
  
  PublicSubnetId:
    Description: Public subnet ID
    Value: !GetAtt SubnetStack.Outputs.PublicSubnetId

  PrivateSubnetId:
    Description: Private subnet ID
    Value: !GetAtt SubnetStack.Outputs.PrivateSubnetId

  WebServerSecurityGroupId:
    Description: Web server security group ID
    Value: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId

  LaunchTemplateId:
    Description: Launch Template ID
    Value: !GetAtt EC2Stack.Outputs.LaunchTemplateId

  AutoScalingGroupName:
    Description: Auto Scaling Group Name
    Value: !GetAtt EC2Stack.Outputs.AutoScalingGroupName

  EC2RoleArn:
    Description: EC2 IAM Role ARN
    Value: !GetAtt EC2Stack.Outputs.EC2RoleArn