AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Stack - Step 5: Complete Web Application with Load Balancer'

Parameters:
  ProjectName:
    Type: String
    Default: aws-practice
    Description: Name of the project
  
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name

  S3BucketName:
    Type: String
    Description: S3 bucket name for CloudFormation templates

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
    Default: aws-practice-keypair

Resources:
  # VPC Stack (from Step 1)
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/templates/vpc.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-vpc-stack

  # Multi-AZ Subnet Stack (Updated for Step 5)
  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/templates/subnet-multi-az.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-subnet-stack

  # Security Groups Stack (from Step 3)
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/templates/security-groups.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-sg-stack

  # Multi-AZ EC2 Stack (Updated for Step 5)
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/templates/ec2-multi-az.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1Id: !GetAtt SubnetStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt SubnetStack.Outputs.PrivateSubnet2Id
        WebServerSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
        KeyPairName: !Ref KeyPairName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-ec2-stack

  # Application Load Balancer Stack (New in Step 5)
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/templates/alb.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1Id: !GetAtt SubnetStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt SubnetStack.Outputs.PublicSubnet2Id
        ALBSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroupId
        AutoScalingGroupName: !GetAtt EC2Stack.Outputs.AutoScalingGroupName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-alb-stack

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
  
  PublicSubnet1Id:
    Description: Public subnet 1 ID
    Value: !GetAtt SubnetStack.Outputs.PublicSubnet1Id

  PublicSubnet2Id:
    Description: Public subnet 2 ID
    Value: !GetAtt SubnetStack.Outputs.PublicSubnet2Id

  PrivateSubnet1Id:
    Description: Private subnet 1 ID
    Value: !GetAtt SubnetStack.Outputs.PrivateSubnet1Id

  PrivateSubnet2Id:
    Description: Private subnet 2 ID
    Value: !GetAtt SubnetStack.Outputs.PrivateSubnet2Id

  ApplicationLoadBalancerDNS:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt ALBStack.Outputs.ApplicationLoadBalancerDNS

  WebsiteURL:
    Description: Website URL
    Value: !GetAtt ALBStack.Outputs.WebsiteURL

  AutoScalingGroupName:
    Description: Auto Scaling Group Name
    Value: !GetAtt EC2Stack.Outputs.AutoScalingGroupName