AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Stack - Step 1: VPC only'

Parameters:
  ProjectName:
    Type: String
    Default: aws-practice
    Description: Name of the project
  
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../templates/vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-vpc-stack

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
  
  VPCCidr:
    Description: VPC CIDR block
    Value: !GetAtt VPCStack.Outputs.VPCCidr

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !GetAtt VPCStack.Outputs.InternetGatewayId